-- 初始化平台核心Schema
CREATE SCHEMA IF NOT EXISTS platform;
CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS permission;

-- 授予openone用户完整权限
GRANT ALL PRIVILEGES ON SCHEMA platform TO openone;
ALTER DEFAULT PRIVILEGES IN SCHEMA platform GRANT ALL ON TABLES TO openone;
ALTER DEFAULT PRIVILEGES IN SCHEMA platform GRANT ALL ON SEQUENCES TO openone;

GRANT ALL PRIVILEGES ON SCHEMA auth TO openone;
ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT ALL ON TABLES TO openone;
ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT ALL ON SEQUENCES TO openone;

GRANT ALL PRIVILEGES ON SCHEMA permission TO openone;
ALTER DEFAULT PRIVILEGES IN SCHEMA permission GRANT ALL ON TABLES TO openone;
ALTER DEFAULT PRIVILEGES IN SCHEMA permission GRANT ALL ON SEQUENCES TO openone;
