-- 初始化平台核心Schema
CREATE SCHEMA IF NOT EXISTS "1000_platform";
CREATE SCHEMA IF NOT EXISTS "1001_auth";
CREATE SCHEMA IF NOT EXISTS "1002_permission";

-- 授予openone用户完整权限
GRANT ALL PRIVILEGES ON SCHEMA "1000_platform" TO openone;
ALTER DEFAULT PRIVILEGES IN SCHEMA "1000_platform" GRANT ALL ON TABLES TO openone;
ALTER DEFAULT PRIVILEGES IN SCHEMA "1000_platform" GRANT ALL ON SEQUENCES TO openone;

GRANT ALL PRIVILEGES ON SCHEMA "1001_auth" TO openone;
ALTER DEFAULT PRIVILEGES IN SCHEMA "1001_auth" GRANT ALL ON TABLES TO openone;
ALTER DEFAULT PRIVILEGES IN SCHEMA "1001_auth" GRANT ALL ON SEQUENCES TO openone;

GRANT ALL PRIVILEGES ON SCHEMA "1002_permission" TO openone;
ALTER DEFAULT PRIVILEGES IN SCHEMA "1002_permission" GRANT ALL ON TABLES TO openone;
ALTER DEFAULT PRIVILEGES IN SCHEMA "1002_permission" GRANT ALL ON SEQUENCES TO openone;
